name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: ProductivityWebApp
  AZURE_WEBAPP_PACKAGE_PATH: "WebDevCWK/bin/Release/net8.0/publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore WebDevCWK/WebDevCWK.sln

    - name: Build
      run: dotnet build WebDevCWK/WebDevCWK.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish WebDevCWK/WebDevCWK.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: dotnet install ef
      run: dotnet tool install -g dotnet-ef

    - name: dotnet bundle migration
      run: dotnet ef migrations bundle --runtime linux-x64 -p DotNetCoreSqlDb/DotNetCoreSqlDb.csproj -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/migrate


    - name: Deployment
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
